type Query {
  hello: String!
  users: [User]
}

type Mutation {
  createUser(input: CreateUserInput!): AuthPayload
}

type User {
  id: ID!
  email: String!
  firstName: String
  lastName: String
  role: Role!
}

type AuthPayload {
  user: User!
  token: String!
}

input CreateUserInput {
  email: String!
  password: String!
}

enum Role {
  ADMIN
  USER
}
